//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOADON
    {
        public Nullable<int> MAHD { get; set; }
        public Nullable<int> MASANPHAMODER { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<double> DONGIAMUA { get; set; }
        public int MACTHD { get; set; }
    
        public virtual SANPHAMODER SANPHAMODER { get; set; }
        public virtual HOADON HOADON { get; set; }
    }
}
