//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWatch.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MATHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATHANG()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
            this.CHITIETPHIEUNHAPs = new HashSet<CHITIETPHIEUNHAP>();
            this.GIOHANGs = new HashSet<GIOHANG>();
        }

        public int MAMATHANG { get; set; }
        [Required(ErrorMessage = "Please enter the Name")]
        public string TENHANG { get; set; }
        public string ANHSANPHAM { get; set; }
        [Required(ErrorMessage = "Please Enter date")]
        public Nullable<System.DateTime> NGAYSANXUAT { get; set; }
        [Required(ErrorMessage = "Please Enter Tenhangsx")]

        public string TENHANGSANXUAT { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập giá trị.")]
        public Nullable<double> GIAHANG { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập LOAI.")]
        public string LOAI { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập BẢO HÀNH")]
        public string BAOHANH { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập Kích thước.")]
        public Nullable<int> KICHTHUOC { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUNHAP> CHITIETPHIEUNHAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }
    }
}